In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
arr1 = np.array([1,2,3])
print(arr1)

print(type(arr1))
print(arr1.shape) # 1차원

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print(type(arr2))
print(arr2.shape) # 2차원

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [8]:
arr3 = np.array([[1,2,3]])

print(type(arr3))
print(arr3.shape) # 2차원

<class 'numpy.ndarray'>
(1, 3)


In [9]:
# ndim(number of dimension) : 몇 차원?

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
2


In [10]:
# arange : array + range
np.arange(3)

array([0, 1, 2])

In [11]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [12]:
# 넘파이 배열 초기화

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# np.zeros_like
# > one_a, one_b 동일한 모양의 0으로 채워진 배열

In [15]:
one_a = np.ones((3,4))

In [16]:
np.zeros_like(one_a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
one_b = np.array([[1,2,3],[4,5,6]])
np.zeros_like(one_b)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
# np.full, np.random and
# np.full()

np.full((4,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [30]:
# np.random()
np.random.seed(100)
print(np.random.random((3,4)))
# 생성할 배열의 크기가 (3,4) 튜플 형태로 인자로 입력됨 (한 번만 전달 받음)
# 0-1 사이

print(np.random.rand(3,4))
# 생성할 배열의 크기가 (3,4) 튜플 형태로 인자로 입력됨 (여러개 인자를 받을 수 있음)
# 0-1 사이

print(np.random.randn(3,4))
# 평균 0, 표준편차 1 >> 표준화 (x-x_bar) / std

[[0.54340494 0.27836939 0.42451759 0.84477613]
 [0.00471886 0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195 0.20920212]]
[[0.18532822 0.10837689 0.21969749 0.97862378]
 [0.81168315 0.17194101 0.81622475 0.27407375]
 [0.43170418 0.94002982 0.81764938 0.33611195]]


In [31]:
np.random.rand(3,4)

array([[0.17541045, 0.37283205, 0.00568851, 0.25242635],
       [0.79566251, 0.01525497, 0.59884338, 0.60380454],
       [0.10514769, 0.38194344, 0.03647606, 0.89041156]])

In [32]:
np.random.rand(3,4,2)

array([[[0.98092086, 0.05994199],
        [0.89054594, 0.5769015 ],
        [0.74247969, 0.63018394],
        [0.58184219, 0.02043913]],

       [[0.21002658, 0.54468488],
        [0.76911517, 0.25069523],
        [0.28589569, 0.85239509],
        [0.97500649, 0.88485329]],

       [[0.35950784, 0.59885895],
        [0.35479561, 0.34019022],
        [0.17808099, 0.23769421],
        [0.04486228, 0.50543143]]])

In [33]:
# np.eye() : 항등 행렬
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
A = np.array([[2,3],
              [8,1],])

print(A)
print()

I = np.eye(2)
print(I)

print()
print(A @ I)



[[2 3]
 [8 1]]

[[1. 0.]
 [0. 1.]]

[[2. 3.]
 [8. 1.]]
